name: Merge Feature Branch to Develop

on:
  push:
    branches:
      - 'historia**'

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-to-develop:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Verificar palabra clave en commit
        id: check-keyword
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"LISTO_PARA_DESARROLLO"* ]]; then
            echo "keyword_found=true" >> $GITHUB_OUTPUT
            echo "✅ Palabra clave 'LISTO_PARA_DESARROLLO' encontrada en el commit"
          else
            echo "keyword_found=false" >> $GITHUB_OUTPUT
            echo "❌ Palabra clave 'LISTO_PARA_DESARROLLO' no encontrada en el commit"
            exit 0
          fi
      
      - name: Configurar Git
        if: steps.check-keyword.outputs.keyword_found == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Mezclar develop en rama de funcionalidad
        if: steps.check-keyword.outputs.keyword_found == 'true'
        run: |
          echo "🔄 Mezclando develop en rama de funcionalidad..."
          git fetch origin develop
          git merge origin/develop --no-edit
          echo "✅ Develop mezclado en rama de funcionalidad"
      
      - name: Instalar dependencias y ejecutar pruebas
        if: steps.check-keyword.outputs.keyword_found == 'true'
        run: |
          echo "🧪 Ejecutando pruebas unitarias en rama de funcionalidad..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m unittest discover -s tests -v
          echo "✅ Todas las pruebas pasaron exitosamente"
      
      - name: Mezclar rama de funcionalidad a develop
        if: steps.check-keyword.outputs.keyword_found == 'true'
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref_name }}
          target-branch: develop
      
      - name: Notificar éxito
        if: steps.check-keyword.outputs.keyword_found == 'true'
        run: |
          echo "🎉 ¡Merge exitoso!"
          echo "Rama ${{ github.ref_name }} mezclada exitosamente a develop"
          echo "Todas las pruebas pasaron correctamente"
